#!/usr/bin/env python3
"""Sync the TCO calculator (Calculator A) from the aenix-org/calculators repo.

The calculator is a private repo; this site vendors two artifacts from it:

  packages/tco/dist         -> static/tco-calculator-app/   (the SPA, iframe widget)
  packages/tco/dist-static  -> content/tco-calculator/**    (indexable hub + spokes)

The static pages are generated from the same data files as the app, so tables,
break-even phrases and prices never drift from the calculator itself. Re-run
this after every quarterly price refresh in the calculators repo:

    npm run tco:build && npm run tco:static     # in the calculators checkout
    python3 scripts/sync-tco-calculator.py ../aenix-calculators
"""

import json
import re
import shutil
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
CONTENT = SITE / "content" / "tco-calculator"
APP = SITE / "static" / "tco-calculator-app"

RELATED = [
    "/alternatives/vmware-alternative/",
    "/migration/vmware/",
    "/products/aenix-platform/",
    "/pricing/",
    "/roi-calculator/",
]


def yaml_str(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def frontmatter(meta: dict, weight: int) -> str:
    lines = [
        "---",
        "# Generated by scripts/sync-tco-calculator.py — do not edit by hand.",
        "# Source of truth: aenix-org/calculators, packages/tco/src/data/*.",
        f"title: {yaml_str(meta['title'])}",
        f"description: {yaml_str(meta['description'])}",
        'type: "page"',
        'language: "en"',
        f"date: {meta['dateModified']}",
        f"lastmod: {meta['dateModified']}",
        f"weight: {weight}",
        f"robots: {yaml_str(meta.get('robots', 'index,follow'))}",
        f"dataset_version: {yaml_str(meta['datasetVersion'])}",
        "related_pages:",
    ]
    lines += [f"  - {page}" for page in RELATED]
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def enable_widget(html: str) -> str:
    """The generator ships the iframe commented out so the fragment stays inert
    outside a Hugo parent. On the site we want the live widget."""
    return re.sub(
        r"<!--\s*(<iframe src=\"/tco-calculator-app/.*?</iframe>)\s*-->",
        r"\1",
        html,
        flags=re.S,
    )


def as_markdown_body(html: str) -> str:
    """Hugo refuses text/html content files under the default security policy,
    so the fragment ships inside a .md file. Goldmark passes a raw HTML block
    through verbatim (markup.goldmark.renderer.unsafe = true) but ends the
    block at the first blank line — hence the blank lines come out."""
    return "\n".join(line for line in html.splitlines() if line.strip()) + "\n"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    repo = Path(sys.argv[1]).expanduser().resolve()
    dist = repo / "packages" / "tco" / "dist"
    static = repo / "packages" / "tco" / "dist-static" / "tco-calculator"
    for path in (dist, static):
        if not path.is_dir():
            print(f"missing {path} — run the tco build in {repo} first")
            return 1

    if APP.exists():
        shutil.rmtree(APP)
    shutil.copytree(dist, APP)

    if CONTENT.exists():
        shutil.rmtree(CONTENT)
    CONTENT.mkdir(parents=True)

    written = []
    for meta_path in sorted(static.rglob("meta.json")):
        meta = json.loads(meta_path.read_text())
        body = as_markdown_body(enable_widget((meta_path.parent / "index.html").read_text()))
        rel = meta_path.parent.relative_to(static)
        if rel == Path("."):
            target, weight = CONTENT / "_index.md", 10
        else:
            target = CONTENT / rel / "index.md"
            target.parent.mkdir(parents=True, exist_ok=True)
            weight = 20 if meta.get("tier") == 1 else 30
        target.write_text(frontmatter(meta, weight) + body)
        written.append(meta["path"])

    print(f"app  -> {APP.relative_to(SITE)}")
    for path in written:
        print(f"page -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
